language: node_js
node_js:
- '6'
- '5'
- '4'
branches:
  only:
  - master
  - "/^release\\/*/"
cache:
  directories:
  - node_modules
notifications:
  email:
    on_success: never
deploy:
  provider: script
  script: scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: master
env:
  global:
  - secure: FZDyjvy/mPHC8sghX25CXKUiEQJzYr3PAAKrbAu5y823ElPoFdh3pwdPN+/mZoLFdaWbwL3sD72Oc6BAjvgoqCcTT+hjEXUytbYFstbYh3ywJOS4+qBsIEint0owiDJn4ZeV/9NC7p72y4NC+yU64sLBjBMdYH2ROmEewnG0o0AAUsLeyZtRVTOMBL9my4LuDyQBEdC0WD5Qmk1Au363zGoemCXTcnsXAr1kfEdA6lkHp/i31rDjWQNiGeZVBiTXI9xZ+CQY6t/WJcj3hovRSH3Jlon2HgO8SEW+CP65zwWFByrQSr2cqBTwKpr8sYWudm5J2s7CX0lRtkx0eHSo3uKBLdj37R9KXQkWpyGuvjwSvtBQ+9ECLOk+KXHXzFumltJ1fcqDuOMj4o0LkwycT3CzbnO1AFQfEBhwd6+exq17WtD3m22ea7T1ntwZIzv1oTRpwpmxR/aSli6emV+xqAN680+K8lX1hI1p8SzlCvYLPvBU4mkvdkLmV43RNnHiM65UwJjVSmiDQlauula9+i7PcWp40skhrVa6HNkDCCdv4vLMNtl+r+RxaeJ4WtgRKlwITwTD4fYq9P7Ys0uSJPJ5ugg0zh703r46B8Ape4jYXppxHlsz0fC9b43ZU4qdwfs6QbqRzFisMnKlfHcKOZx0y5Ktl3wqHUEON6XKkfc=
